name: Export LinkedIn Badge

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  badge:
    uses: curiousvlxd/linkedin-badge-renderer/.github/workflows/export.yml@main
    with:
      handle: "vladtimchenko"
      theme: "dark"
      output_branch: "linkedin-badge"
      out: "output.svg"